version: 2

jobs:
  "build_image":
    docker: &DOCKERIMAGE
      - image: jenkinsrise/gcloud-nodejs-npm-redis:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: "echo Building version ${CIRCLE_SHA1}"
      - run: "echo ${ACCT_AUTH} | base64 -d -i > ${HOME}//gcloud-service-key.json"
      - run: gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
      - run: gcloud config set project $PROJECT_ID
      - setup_remote_docker
      - run: docker build -t $DOCKER_IMAGE_NAME:${CIRCLE_SHA1} .
      - run: docker images
      - run: docker save $DOCKER_IMAGE_NAME:${CIRCLE_SHA1} > dockerImage.tar
      - persist_to_workspace:
          root: .
          paths:
            - dockerImage.tar

  "deploy":
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: "echo ${ACCT_AUTH} | base64 -d -i > ${HOME}//gcloud-service-key.json"
      - run: gcloud --quiet config set container/cluster messaging-service-load-test
      - run: gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
      - run: gcloud config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
      - run: gcloud config set project $PROJECT_ID
      - run: gcloud --quiet container clusters get-credentials messaging-service-load-test
      - run: echo "Pushing image $DOCKER_IMAGE_NAME to registry..."
      - setup_remote_docker
      - run: docker load < ./dockerImage.tar
      - run: docker tag ${DOCKER_IMAGE_NAME}:${CIRCLE_SHA1} gcr.io/$PROJECT_ID/$DOCKER_IMAGE_NAME:$CIRCLE_SHA1
      - run: gcloud auth configure-docker
      - run: docker push gcr.io/${PROJECT_ID}/${DOCKER_IMAGE_NAME}:${CIRCLE_SHA1}
      - run: kubectl patch deployment messaging-service-load-test -p '{"spec":{"template":{"spec":{"containers":[{"name":"messaging-service-load-test","image":"'"$DOCKER_IMAGE_NAME"':'"${CIRCLE_SHA1}"'"}]}}}}'

workflows:
  version: 2
  workflow1:
    jobs:
      - "build_image"
      - "deploy":
          requires:
            - build_image
          filters:
            branches:
              only:
                - master
